version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          RACK_ENV: test

    steps:
      - checkout

      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run: bundle exec rspec --backtrace
      - run: bundle exec rubocop

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test
